version: '2'
services:
  wordpress:
    image: wordpress:latest 
    ports:
      - 8085:80 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
  db:
    image: mariadb:latest 
    ports:
      - 3306:3306 
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
